export const BUSINESS_LABELS = {
  mobiles: {
    maintenance: 'استلام صيانة',
    imei: 'IMEI / السيريال',
    software: 'تفليش / برمجة',
    balance: 'عمليات الرصيد',
    deviceBrand: 'ماركة الجهاز',
    deviceModel: 'موديل الجهاز',
    issue: 'العطل / المشكلة',
    lockPattern: 'رمز القفل / النمط',
    devicePhoto: 'صورة الجهاز',
  },
  clothing: {
    maintenance: 'تعديل ملابس',
    imei: 'المقاس',
    software: 'اللون',
    balance: 'الماركة / البراند',
    deviceBrand: 'الماركة',
    deviceModel: 'الموديل / التصميم',
    issue: 'التعديل المطلوب',
    lockPattern: 'الموسم (صيفي/شتوي)',
    devicePhoto: 'صورة القطعة',
  },
  grocery: {
    maintenance: 'طلبية خاصة',
    imei: 'تاريخ الانتهاء',
    software: 'وحدة القياس',
    balance: 'الوزن / الحجم',
    deviceBrand: 'الشركة المصنعة',
    deviceModel: 'الصنف',
    issue: 'ملاحظات التخزين',
    lockPattern: 'رقم الرف',
    devicePhoto: 'صورة المنتج',
  },
  pharmacy: {
    maintenance: 'صرف روشتة',
    imei: 'الاسم العلمي',
    software: 'تاريخ الصلاحية',
    balance: 'الشركة المنتجة',
    deviceBrand: 'الماركة التجارية',
    deviceModel: 'الدواء',
    issue: 'طريقة الاستخدام',
    lockPattern: 'مكان الرف',
    devicePhoto: 'صورة الدواء',
  },
  restaurant: {
    maintenance: 'طلب مطبخ',
    imei: 'رقم الطاولة',
    software: 'نوع الطلب (محلي/سفري)',
    balance: 'الإضافات',
    deviceBrand: 'القسم',
    deviceModel: 'الوجبة',
    issue: 'ملاحظات الطبخ',
    lockPattern: 'عدد الأشخاص',
    devicePhoto: 'صورة الوجبة',
  },
  construction: {
    maintenance: 'طلب توريد',
    imei: 'كود المادة',
    software: 'المواصفات الفنية',
    balance: 'المورد',
    deviceBrand: 'النوع',
    deviceModel: 'المادة',
    issue: 'مكان التسليم',
    lockPattern: 'رقم الدفعة',
    devicePhoto: 'صورة العينة',
  },
  tailoring: {
    maintenance: 'فحص مقاس',
    imei: 'الطول / العرض',
    software: 'نوع القماش',
    balance: 'التطريز',
    deviceBrand: 'الخياط',
    deviceModel: 'الموديل / التصميم',
    issue: 'الملاحظات / التفصيل',
    lockPattern: 'تاريخ الاستلام',
    devicePhoto: 'صورة الموديل',
  },
  wholesale: {
    maintenance: 'طلبية تاجر',
    imei: 'كود التوزيع',
    software: 'تاريخ الدفعة',
    balance: 'عمليات الرصيد',
    deviceBrand: 'المصنع',
    deviceModel: 'الصنف',
    issue: 'موقع التسليم / المحل',
    lockPattern: 'حالة الحجز',
    devicePhoto: 'صورة الصنف',
  },
  master_wholesale: {
    maintenance: 'شحنة دولية',
    imei: 'رقم بوليصة الشحن',
    software: 'بلد المنشأ',
    balance: 'حالة الحاويات',
    deviceBrand: 'العلامة التجارية',
    deviceModel: 'المنتج المستورد',
    issue: 'ملاحظات الجمرك',
    lockPattern: 'تاريخ الوصول المتوقع',
    devicePhoto: 'صورة المنتج / الكرتون',
  }
};

export const BRANDS = [
  'Samsung', 'Apple', 'Xiaomi', 'Huawei', 'Oppo', 'Vivo', 'Realme', 'Infinix', 'Tecno', 'Itel', 'Nokia', 'LG', 'Sony', 'Google', 'OnePlus', 'Motorola', 'Honor', 'ZTE'
];
